import base64
from typing import Dict, Any
from app.tools.github.auth import get_installation_token
from app.tools.github.client import GitHubClient
from app.models.security import JWTToken

async def read_github_file(
    repo_owner: str, 
    repo_name: str, 
    file_path: str, 
    user_context: JWTToken
) -> Dict[str, Any]:
    """Tool: Read the contents of a file directly from a GitHub repository."""
    
    # In an enterprise, verify user_context.tenant_id is allowed to access repo_owner/repo_name here!
    
    try:
        token = await get_installation_token(repo_owner, repo_name)
        if token.startswith("mock_gh_token"):
            return {"success": True, "content": f"# Mock README for {repo_owner}/{repo_name}\n\nHello from Phase 7"}

        client = GitHubClient(token)
        
        # Use the Contents API
        result = await client.get(f"repos/{repo_owner}/{repo_name}/contents/{file_path}")
        
        # GitHub returns file content base64 encoded
        content = base64.b64decode(result["content"]).decode('utf-8')
        
        await client.close()
        return {"success": True, "content": content}
    except Exception as e:
        return {"success": False, "error": str(e)}

async def create_pull_request(
    repo_owner: str,
    repo_name: str,
    title: str,
    body: str,
    head_branch: str,
    base_branch: str,
    user_context: JWTToken
) -> Dict[str, Any]:
    """Tool: Create a new Pull Request."""
    
    try:
        token = await get_installation_token(repo_owner, repo_name)
        if token.startswith("mock_gh_token"):
            return {
                "success": True, 
                "pr_url": f"https://github.com/{repo_owner}/{repo_name}/pull/1",
                "pr_number": 1
            }

        client = GitHubClient(token)
        
        payload = {
            "title": title,
            "body": f"{body}\n\n*Auto-generated by NexusMCP on behalf of {user_context.sub}*",
            "head": head_branch,
            "base": base_branch
        }
        
        result = await client.post(f"repos/{repo_owner}/{repo_name}/pulls", payload)
        await client.close()
        
        return {
            "success": True, 
            "pr_url": result["html_url"],
            "pr_number": result["number"]
        }
    except Exception as e:
        return {"success": False, "error": str(e)}
